spring:
    application:
        name: sqlexercise
    datasource:
        url: jdbc:mysql://localhost:3306/sqlexercise
#        url: jdbc:mysql://localhost:3306/sqlexercise?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=GMT%2B8&characterEncoding=utf8
#        url: jdbc:mysql://localhost:3306/sqlexam?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=GMT%2B8&characterEncoding=utf8
        username: root
        password: wybwyb1223
        driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
        host: localhost
        port: 6379
        database: 0
        connect-timeout: 30
mybatis:
    mapper-locations: classpath:dataImpl/*Mapper.xml
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
